### ISSUE TITLE
Trusting all SSL certificates

### ISSUE THREAD

**Issue by mdprasadeng** [yammer/dropwizard-auth-ldap#6]
Hey,

I need to access our internal LDAP server and hence want to switch trust all connections as the current certificate is causing issues (tried adding it as certificate via keytool too). 

There are ways to set trust all connections for HTTPS protocol, can someone help in doing the same for ldaps ?

Regards,
Durga

**Comment by chrisgray** [comment]
After you've added the certificate to the keystore/truststore. Are you also making sure that the JVM leverages this new store?

                -Djavax.net.ssl.keyStore=path/to/your/keystore
                -Djavax.net.ssl.keyStorePassword=keystore-password
                -Djavax.net.ssl.trustStore=path/to/your/keystore
                -Djavax.net.ssl.trustStorePassword=keystore-password
