### ISSUE TITLE
authenticateAndReturnPermittedGroups and authenticate treat "RestrictedGroups" differently

### ISSUE THREAD

**Issue by maheshkelkar** [yammer/dropwizard-auth-ldap#7]
In LdapAuthenticator::authenticate() - if restrictedGroups is not configured, then intersection of user groups with restrcitedGroups is *skipped*. As a result user is authenticated successfully.

But, LdapAuthenticator:authenticateAndReturnPermittedGroups - if restrictedGroups is not configured, then intersection is still enforced and resultantly authentication is denied.

IMO, the behavior doesn't match and should be changed from:
```java
   private Set<String> getGroupMembershipsIntersectingWithRestrictedGroups(
   ::
                if (configuration.getRestrictToGroups().contains(group)) {
                        overlappingGroups.add(group);
                }
```
to:
```java
   private Set<String> getGroupMembershipsIntersectingWithRestrictedGroups(
   ::
                if (configuration.getRestrictToGroups().isEmpty() ||
                            configuration.getRestrictToGroups().contains(group)) {
                        overlappingGroups.add(group);
                }
```

**Comment by chrisgray** [comment]
I agree, this makes sense. I'll make this change in the following release.
